name: Update Server

on:
  schedule:
    - cron: '* * * * *'

jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update server
        run: |
          ssh -i ${{ secrets.MY_NEW_KEY_PAIR }} ubuntu@65.0.93.250 "sudo apt update && sudo apt upgrade"
