name: SSH into VM

on:
  push:
    branches:
      - master

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa vm-ip-address >> ~/.ssh/known_hosts

    - name: SSH into VM
      run: ssh -i ~/.ssh/id_rsa ubuntu@ec2-13-127-154-254.ap-south-1.compute.amazonaws.com "echo 'This is something I did in the server' > /tmp/something.txt"
