name:  Server Update

on:
  schedule:
    - cron: '* * * * *'

jobs:
  do-something-in-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Do something in server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@13.127.154.254 "echo 'This is something I did in the server' > /tmp/something.txt"
