name: SSL Expiry Alert

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-ssl-expiry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install pyopenssl requests
      - name: Get domain names
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: cat domains.txt
      - name: Check SSL expiry
        run: |
          for domain in $(cat domains.txt); do
            echo "Checking SSL expiry for $domain"
            ssl_expiry=$(openssl s_client -connect $domain:443 2>/dev/null | openssl x509 -enddate -noout | cut -d'=' -f2 | cut -d'-' -f1)
            days_to_expiry=$(echo $(($(date -d "$ssl_expiry" +%s) - $(date +%s))) / 86400)
            if [ $days_to_expiry -le 730 ]; then
              slack_message="SSL Expiry Alert
                * Domain : $domain
                * Warning : The SSL certificate for $domain will expire in $days_to_expiry days."
              curl -X POST -H 'Content-Type: application/json' -d '{ "text": "$slack_message" }' $SLACK_WEBHOOK_URL
            fi
          done
