name: SSL Expiry Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  ssl_expiry_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -g certbot

      - name: Run SSL Expiry Check
        run: |
          # Get the list of domains from a file
          domains=$(cat domains.txt)

          # Check the SSL expiry status for each domain
          for domain in $domains; do
            days_left=$(certbot certificates | grep "$domain" | awk '{print $4}')

            # Send an alert notification if the SSL certificate is about to expire
            if [ "$days_left" -lt 30 ]; then
              message="SSL Expiry Alert\n* Domain : $domain\n* Warning : The SSL certificate for $domain will expire in $days_left days."
              curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$message\"}" $SLACK_WEBHOOK_URL
            fi
          done
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
