name: SSL Expiry Check

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'  # Run every day at midnight UTC

jobs:
  ssl_expiry_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install -g date-fns

      - name: Run SSL Expiry Check
        run: |
          # Read the list of domains from a file (one domain per line)
          while IFS= read -r domain; do
            expiry_date=$(echo | openssl s_client -servername "$domain" -connect "$domain":443 2>/dev/null | openssl x509 -noout -dates | grep "notAfter" | cut -d "=" -f 2)
            expiry_unix=$(date -d "$expiry_date" +%s)
            current_unix=$(date +%s)
            days_left=$(( (expiry_unix - current_unix) / 86400 ))

            if [ "$days_left" -lt 30000 ]; then
              message="SSL Expiry Alert\n* Domain : $domain\n* Warning : The SSL certificate for $domain will expire in $days_left days."
              curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$message\"}" $SLACK_WEBHOOK_URL
            fi
          done < domains.txt
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
