name: SSL Expiry Check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-ssl-expiry:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSL expiry
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install pyOpenSSL
      - name: Get domain names
        run: echo "www.google.com" > domains.txt
      - name: Check SSL expiry for each domain
        run: |
          while IFS= read -r domain; do
            python check_ssl_expiry.py "$domain"
          done < domains.txt
